Name:           ros-kinetic-libqsopt
Version:        0.6.11
Release:        0%{?dist}
Summary:        ROS libqsopt package

Group:          Development/Libraries
License:        free for research or education purpose, all rights maintained by David Applegate, William Cook, Sanjeeb Dash, and Monika Mevenkamp
URL:            http://www.math.uwaterloo.ca/~bico/qsopt/index.html
Source0:        %{name}-%{version}.tar.gz

Requires:       dpkg
BuildRequires:  dpkg
BuildRequires:  ros-kinetic-catkin

%description
Wrapper for the Qsopt linear programming solver. The code was obtained from
http://www.math.uwaterloo.ca/~bico/qsopt/index.html, all rights on Qsopt go to
the authors David Applegate, William Cook, Sanjeeb Dash, and Monika Mevenkamp.
The library doesn't explicitly provide a license, but allows the free use for
research or educational purposes. For further questions on licensing, contact
the previous listed authors.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon Jul 17 2017 Richard Bormann <richard.bormann@ipa.fraunhofer.de> - 0.6.11-0
- Autogenerated by Bloom

